#!/bin/sh

# start_daemon, killproc, status_of_proc, log_*, etc.
. /etc/rc.d/init.d/functions

    
#NAME=/root/bot/BotCambioDeContrasena
   

case "$1" in
start)
   nohup /root/usr/sbin/BotCambioDeContrasena.sh > /dev/null 2>&1 &
   echo $!>/var/run/BotCambioDeContrasena.sh.pid
   ;;
stop)
   pkill -P `cat /var/run/BotCambioDecontrasena.sh.pid`
   rm /var/run/BotCambioDeContrasena.sh.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/BotCambioDeContrasena.sh.pid ]; then
      echo BotCambioDeContrasena.sh is running, pid=`cat /var/run/BotCambioDeContrasena.sh.pid`
   else
      echo BotCambioDeContrasena.sh is not running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
